config/routes.rb
SexualIq::Application.routes.draw do

  root 'welcome#index'
  get 'welcome/quiz'
  get 'welcome/thequiz'

  resources :results

end

app/models/result.rb
class Result < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
	def new
	end

	def create
		@result = Result.new(result_params)
 	
	  @result.save
	  redirect_to @result
	end

	def show
	  @result = Result.find(params[:id])
	end

	def index
		@results = Result.all
	end

	private
	  def result_params
	    params.require(:result).permit(:age, :school, :zip_code, :score, :bracket)
	  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SexualIq</title>
  <link href='//fonts.googleapis.com/css?family=Source+Sans+Pro:300' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
</head>
<body>
<% 
=begin
%>
	<div class="navbar navbar-fixed-top">
      <div class="navbar-inner navbar-inner2" id="header-bar">
        <div class="container-fluid">
          <div class="col-md-12 centered"> 
            <!--<img src="images/" class="img" />-->
            <h1 style="text-align: center;">What's your sexual IQ?</h1>
          </div> 
        </div>
      </div>
    </div>
<%
=end
%>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12 .col-xs-12 .col-sm-12">
        <div class="row">
          <%= yield :header_menu %>
          <%= yield :top_menu %>
        </div>
      </div>
    </div>
  </div>

  <div class="container-fluid">
	  <div class="row">
	    <div class="col-md-12 .col-xs-12 .col-sm-12">
	      <div class="row">
					<%= yield %>
				</div>
			</div>
		</div>
	</div>

</body>
</html>

app/views/results/index.html.erb
<!--index to retrieve all the quizzes taken-->

app/views/results/show.html.erb
<%
=begin
%>
<% content_for :top_menu do %>
  <div class=".col-xs-12 .col-sm-6 .col-sm-offset-3 col-md-4 col-md-offset-4">
    <div class="frame">
      <div class="center">
        <h3 style="display:inline-block;">Your</h3>
        <h3 style="color: #9013fe;display:inline-block;margin-left:-9px;">sexpert</h3>
        <h3 style="display:inline-block;margin-left:-9px;">results:</h3>
      </div>
    </div>
    <%#= image_tag "quizheading.png", style: "width: 371px; height: auto; margin-top:10px;" %>
  </div>
<% end %>
<%
=end
%>

<div class=".col-xs-12 .col-sm-6 .col-sm-offset-3 col-md-4 col-md-offset-4" style="text-align: center;">
	<div class="frame">
		<p style="font-size:20px;text-indent:20px;margin:15px;text-align:left;"><%= @result.bracket %></p>
		<div style="clear:both; height: 20px; width:100%;"></div>
		<p style="font-size:30px;display:inline-block;">Score:</p><p style="font-size:30px;display:inline-block;color: #9013fe;margin-left:8px;"><%= @result.score %>%</p>
		<div style="clear:both; height: 20px; width:100%;"></div>

    <%= render partial: 'welcome/social_share' %>
		<%#= link_to('Share on Facebook', 'https://www.facebook.com/dialog/feed?
                                  link=https://developers.facebook.com/docs/reference/dialogs/&
                                  picture=http://fbrell.com/f8.jpg&
                                  name=Facebook%20Dialogs&
                                  caption=Reference%20Documentation&
                                  description=Using%20Dialogs%20to%20interact%20with%20users.&
                                  redirect_uri=http://mighty-brushlands-5068.herokuapp.com/',
                                  :target => :blank) %>


		<!-- <a href="#" 
            onclick="
              window.open(
                'https://www.facebook.com/sharer/sharer.php?u='+encodeURIComponent(location.href), 
                'facebook-share-dialog', 
                'width=626,height=436'); 
              return false;"> -->
      <%#= image_tag "http://icons.iconarchive.com/icons/icontexto/social-inside/256/social-inside-facebook-icon.png", style: "width: 20%;height:auto;" %>
    </a>
	</div>
</div>

<!-- <div class="col-md-4 col-md-offset-4">
	<div class="frame"></div>
	<%#= image_tag "citychart.png", style: "width: 371px; height: auto; margin-top:10px;" %>
</div> -->

<div class=".col-xs-12 .col-sm-6 .col-sm-offset-3 col-md-4 col-md-offset-4">
	<div class="frame">
		<p style="margin: 10px;font-size:18px;">If you have any questions, contact us at <a href="http://yourRealityCheck.org/ask-a-question">YourRealityCheck.org/ask-a-question</a>.</p>
		<p style="margin: 10px;font-size:18px;">To schedule free STD or pregnancy testing, or to talk with a medical professional, visit our clinic website: <a href="http://wpclinic.org">Wpclinic.org</a>.</p>
	</div>
</div>

<div style="display:none;">
	<p>
		<strong>Age:</strong>
		<%= @result.age %>
	</p>
	<p>
		<strong>School:</strong>
		<%= @result.school %>
	</p>
	<p>
		<strong>Zip code:</strong>
		<%= @result.zip_code %>
	</p>
	<p>
		<strong>Score:</strong>
		<%= @result.score %>
	</p>
</div>

app/views/welcome/_social_share.html.erb
<a href="#" 
  onclick="
    window.open(
      'https://www.facebook.com/sharer/sharer.php?u='+encodeURIComponent(location.href), 
      'facebook-share-dialog', 
      'width=626,height=436'); 
    return false;"> 
  <%= image_tag "http://icons.iconarchive.com/icons/icontexto/social-inside/256/social-inside-facebook-icon.png", style: "width: 20%;height:auto;" %>
</a>

<%
=begin
%>
<%= twitter_button %>
<%= facebook_button %>
<%= pinterest_button %>
<%= linkedin_button %>
<%= reddit_button %>
<%= google_plus_button %>
<%= tumblr_button %>
<%= stumble_upon_button %>


<!-- even older -->
<ul class="social_share">
  <li>
    <%= twitter_button %>
  </li>
  <li>
    <%= facebook_button %>
  </li>
  <li>
    <%= pinterest_button %>
  </li>
  <li>
    <%= linkedin_button %>
  </li>
  <li>
    <%= reddit_button %>
  </li>
  <li>
    <%= google_plus_button %>
  </li>
  <li>
    <%= tumblr_button %>
  </li>
  <li>
    <%= stumble_upon_button %>
  </li>
</ul>
<%
=end
%>

app/views/welcome/index.html.erb
<div class=".col-xs-12 .col-sm-6 .col-sm-offset-3 col-md-4 col-md-offset-4" style="text-align: center;">
  <div class="frame_invisible">
    <div style="margin-top:20px;margin-bottom: 20px;">
      <div>
        <%= image_tag "RealityCheck_logo_png_format.png", style: "width: 50%;height:auto;" %>
      </div>
    </div> 
    <div>
      <p style="font-size:35px;display:inline-block;">Are you a</p><p style="font-size:35px;display:inline-block;color: #9013fe;margin-left:8px;"> sexpert?</p>
    </div>
    <div style="margin-top: 80px;">
      <%= link_to 'Take the Quiz', new_result_path, class: "btn btn-default btn_quiz" %>
    </div>
    <div style="margin-top: 20px;">
      <%= render partial: 'social_share' %>
    </div>
  </div>
</div>

<!--
<a href="javascript:void(0);"><button class="btn btn-next">&rarr;</button></a>
</h4>
-->

app/views/welcome/quiz.html.erb
<!--coolness-->
<script>
	// hello
	var score = 0;

	var questions = [
		['Using two condoms is safer.', 'false'],
		['You need a parent to get advice.', 'false'],
		['You cannot get sexually transmitted diseases through anal sex.', 'false'],
		['Sex is fun.', 'true'],
		['If you are having sex you are taking a risk.', 'true'],
		['Happy relationships exist without sex', 'true'], 	
	];

	function askQuestion(question) {
		var answer = prompt(question[0],'');
			if (answer == question[1]) {
				alert('Correct!');
				score++;
			} else {
				alert('Sorry. The correct answer is ' + question[1]);
			};
	};

	for (var i=0; i<questions.length; i++) {
		askQuestion(questions[i]);
	};
</script>

<script>
	var message = 'You got ' + score;
	message += ' out of ' + questions.length;
	message += ' questions correct.';
	document.write('<p style="margin-top: 40%;text-align:center;">' + message + '</p>');
</script>

app/views/welcome/thequiz.html.erb
  <div id = "frame"
    role = "content" >

<script>
 var quiztitle = "What's Your Sexual IQ?";


 var quiz = [
        {
            "question" : "Q1: Using two condoms is safer.",
            //"image" : "http://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Albert_Einstein_Head.jpg/220px-Albert_Einstein_Head.jpg",
            "choices" : [
                                    "True",
                                    "False"
                                ],
            "correct" : "False",
            "explanation" : "Using two condoms increases the chances of breakage.",
        },
        {
            "question" : "You need a parent to get advice.",
            //"image" : "http://upload.wikimedia.org/wikipedia/commons/thumb/9/94/US_%242_obverse-high.jpg/320px-US_%242_obverse-high.jpg",
            "choices" : [
                                    "True",
                                    "False"
                                ],
            "correct" : "False",
            "explanation" : "You do not need a parent to get advice.  In fact there are many resources local to Los Angeles like clarishealth.org.",
        },
        {
            "question" : "You cannot get sexually transmitted diseases through anal sex.",
            //"image" : "",
            "choices" : [
                                    "True",
                                    "False"
                                ],
            "correct" : "False",
            "explanation" : "You are just as susceptible to STD's doing anal intercourse as you are doing vaginal.  To reduce your risk use a condom.  To eliminate your risk practice, practice abstinence.  But hey who wants that?",
        },
     

    ];


 var currentquestion = 0,
     score = 0,
     submt = true,
     picked;

 jQuery(document).ready(function ($) {


     function htmlEncode(value) {
         return $(document.createElement('div')).text(value).html();
     }


     function addChoices(choices) {
         if (typeof choices !== "undefined" && $.type(choices) == "array") {
             $('#choice-block').empty();
             for (var i = 0; i < choices.length; i++) {
                 $(document.createElement('li')).addClass('choice choice-box').attr('data-index', i).text(choices[i]).appendTo('#choice-block');
             }
         }
     }

     function nextQuestion() {
         submt = true;
         $('#explanation').empty();
         $('#question').text(quiz[currentquestion]['question']);
         $('#pager').text('Question ' + Number(currentquestion + 1) + ' of ' + quiz.length);
         if (quiz[currentquestion].hasOwnProperty('image') && quiz[currentquestion]['image'] != "") {
             if ($('#question-image').length == 0) {
                 $(document.createElement('img')).addClass('question-image').attr('id', 'question-image').attr('src', quiz[currentquestion]['image']).attr('alt', htmlEncode(quiz[currentquestion]['question'])).insertAfter('#question');
             } else {
                 $('#question-image').attr('src', quiz[currentquestion]['image']).attr('alt', htmlEncode(quiz[currentquestion]['question']));
             }
         } else {
             $('#question-image').remove();
         }
         addChoices(quiz[currentquestion]['choices']);
         setupButtons();


     }


     function processQuestion(choice) {
         if (quiz[currentquestion]['choices'][choice] == quiz[currentquestion]['correct']) {
             $('.choice').eq(choice).css({
                 'background-color': '#50D943'
             });
             $('#explanation').html('<strong>Correct!</strong> ' + htmlEncode(quiz[currentquestion]['explanation']));
             score++;
         } else {
             $('.choice').eq(choice).css({
                 'background-color': '#D92623'
             });
             $('#explanation').html('<strong>Incorrect.</strong> ' + htmlEncode(quiz[currentquestion]['explanation']));
         }
         currentquestion++;
         $('#submitbutton').html('NEXT QUESTION &raquo;').on('click', function () {
             if (currentquestion == quiz.length) {
                 endQuiz();
             } else {
                 $(this).text('Check Answer').css({
                     'color': '#222'
                 }).off('click');
                 nextQuestion();
             }
         })
     }


     function setupButtons() {
         $('.choice').on('mouseover', function () {
             $(this).css({
                 'background-color': '#e1e1e1'
             });
         });
         $('.choice').on('mouseout', function () {
             $(this).css({
                 'background-color': '#fff'
             });
         })
         $('.choice').on('click', function () {
             picked = $(this).attr('data-index');
             $('.choice').removeAttr('style').off('mouseout mouseover');
             $(this).css({
                 'border-color': '#222',
                 'font-weight': 700,
                 'background-color': '#c1c1c1'
             });
             if (submt) {
                 submt = false;
                 $('#submitbutton').css({
                     'color': '#000'
                 }).on('click', function () {
                     $('.choice').off('click');
                     $(this).off('click');
                     processQuestion(picked);
                 });
             }
         })
     }


     function endQuiz() {
         $('#explanation').empty();
         $('#question').empty();
         $('#choice-block').empty();
         $('#submitbutton').remove();
         $('#question').text("You got " + score + " out of " + quiz.length + " correct.");
         $(document.createElement('h2')).css({
             'text-align': 'center',
             'font-size': '4em'
         }).text(Math.round(score / quiz.length * 100) + '%').insertAfter('#question');
   
     }


     function init() {
         //add title
         if (typeof quiztitle !== "undefined" && $.type(quiztitle) === "string") {
             $(document.createElement('h1')).text(quiztitle).appendTo('#frame');
         } else {
             $(document.createElement('h1')).text("Quiz").appendTo('#frame');
         }

         //add pager and questions
         if (typeof quiz !== "undefined" && $.type(quiz) === "array") {
             //add pager
             $(document.createElement('p')).addClass('pager').attr('id', 'pager').text('Question 1 of ' + quiz.length).appendTo('#frame');
             //add first question
             $(document.createElement('h2')).addClass('question').attr('id', 'question').text(quiz[0]['question']).appendTo('#frame');
             //add image if present
             if (quiz[0].hasOwnProperty('image') && quiz[0]['image'] != "") {
                 $(document.createElement('img')).addClass('question-image').attr('id', 'question-image').attr('src', quiz[0]['image']).attr('alt', htmlEncode(quiz[0]['question'])).appendTo('#frame');
             }
             $(document.createElement('p')).addClass('explanation').attr('id', 'explanation').html('&nbsp;').appendTo('#frame');

             //questions holder
             $(document.createElement('ul')).attr('id', 'choice-block').appendTo('#frame');

             //add choices
             addChoices(quiz[0]['choices']);

             //add submit button
             $(document.createElement('div')).addClass('choice-box').attr('id', 'submitbutton').text('Check Answer').css({
                 'font-weight': 700,
                 'color': '#222',
                 'padding': '30px 0'
             }).appendTo('#frame');

             setupButtons();
         }
     }

     init();
 });
</script>